### ISSUE TITLE
Fails to unlock

### ISSUE THREAD

**Issue by bhepple** [jovanlanik/gtklock#1]
Hate to be the first but ...

I tried running gtklock with -l, -d or -i options as well as unadorned and it failed to accept my password.
```
sway-1.6.1-4.fc35.x86_64
wlroots-0.14.1-3.fc35.x86_64
```

**Comment by jovanlanik** [comment]
Did you install the program using `$ make install`? If not, you are missing the pam configuration file.

**Comment by bhepple** [comment]
That was it - thanks. Good to get these simple ones out of the way and documented for other idiots!!
