### ISSUE TITLE
[Fedora 39] gtklock: error while loading shared libraries: libgtk-session-lock.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ModcoLocko** [jovanlanik/gtklock#100]
I have compiled both libgtk-session-lock and gtklock (and installed them)

## files of /usr/local/lib64/

```
total 432
drwxr-xr-x. 1 root root      0 Jul 20  2023 bpf
drwxr-xr-x  1 root root     52 Jul 10 21:08 girepository-1.0
lrwxrwxrwx  1 root root     24 Jul 10 21:08 libgtk-session-lock.so -> libgtk-session-lock.so.0
lrwxrwxrwx  1 root root     28 Jul 10 21:08 libgtk-session-lock.so.0 -> libgtk-session-lock.so.0.2.0
-rwxr-xr-x  1 root root 431496 Jul 10 19:52 libgtk-session-lock.so.0.2.0
drwxr-xr-x  1 root root     42 Jul 10 21:08 pkgconfig
```
From what it looks like to me the binary for `libgtk-session-lock.so.0` does exist but is not in the correct place?

Do I need to create a symlink somewhere else for gtklock to be able to find it?

**Comment by jovanlanik** [comment]
Try running `ldconfig` as root.

**Comment by ModcoLocko** [comment]
> Try running `ldconfig` as root.

I had already done that, and have done it again, same result.

**Comment by jovanlanik** [comment]
Well, this isn't really an issue with gtklock.
I would try setting the libdir option to /usr/local/lib in meson when building and installing gtk-session-lock. I'm not sure if ld.so is configured to search /usr/local/lib64. You can also check /etc/ld.so.conf and /etc/ld.so.conf.d...

**Comment by ModcoLocko** [comment]
I didn't have /usr/local/lib64 or /usr/local/lib configured in /etc/ld.so.conf

Adding 
```
/usr/local/lib64
/usr/local/lib 
```
to `/etc/ld.so.conf`,
and running `ldconfig` fixed it.

Thank you for your help!
