### ISSUE TITLE
Black screen with "Error 71 (Protocol error) dispatching to Wayland display" with fprintd

### ISSUE THREAD

**Issue by vunnyso** [jovanlanik/gtklock#101]
Using latest 7b016fd86926843233e61af4907594cbbc050bd7 commit,  I am getting black screen issue.

**Steps to reproduce:**
1) First enroll using fprintd-enroll -f right-index-finger
2) Lock screen using windows + l 
3) Enter wrong password and place wrong finger
4) Repeat step 3 few times

**Reproducibility**:  Always

**Logs**
labwc[675]: [3808369.503]  -> wl_display@1.error(ext_session_lock_surface_v1@30, 2, "committed surface dimensions do not match last acked configure")
labwc[675]: 00:01:16.296 [INFO] [wayland] error in client communication (pid 857)
labwc[857]: [3808370.065] wl_display@1.delete_id(36)
labwc[857]: [3808370.075] wl_display@1.delete_id(39)
labwc[857]: [3808370.077] wl_display@1.delete_id(37)
labwc[857]: [3808370.079] wl_display@1.error(ext_session_lock_surface_v1@30, 2, "committed surface dimensions do not match last acked configure")
**.gtklock-wrappe[857]: Error 71 (Protocol error) dispatching to Wayland display.**

**Environment:** 
Compositor: Labwc

**Additional Note:**
Similar signature mentioned in https://github.com/jovanlanik/gtklock/issues/72#issuecomment-2183979329

**Comment by vunnyso** [comment]
**Root cause** for the failure is Overflow of widgets.
As we keeping on adding widgets in GTK container [here](https://github.com/jovanlanik/gtklock/blob/master/src/window.c#L83) but we never remove widgets resulting it will exceed screen size and wayland cannot render dimensions outside screen size. 

**Example**: As captured in situation where its almost reached boundary and entering wrong credentials will cause wayland error/black screen. 
![image](https://github.com/user-attachments/assets/3454d95a-9ef1-48d7-93f3-d302d4a7385a)

**Comment by jovanlanik** [comment]
Can you try the latest master? I put the messages in a scrollable window so they shouldn't overflow.

**Comment by vunnyso** [comment]
Thank you so much @jovanlanik for the quick fix, I **NO** longer see black screen issue on my side with e0e7f6d5ae7667fcc3479b6732046c67275b2f2f commit.

However there is no scroll bar in scrollable window and side note nothing is happening if I click on cross buttons.
![image](https://github.com/user-attachments/assets/5bf2599f-ed2e-4cd0-8779-fa2bd70dcd83)

**Comment by jovanlanik** [comment]
I would like to test it more and see if I can replicate your issue. I'm just not sure when I'll get around to it.

**Comment by vunnyso** [comment]
Alright thanks, then I will leave this issue still open while waiting for your update.

**Comment by jovanlanik** [comment]
I can't replicate. Are you sure this isn't an issue just on your patched version? Can you try building from master?

**Comment by vunnyso** [comment]
Thanks @jovanlanik issue is not reproducible with latest master, hence closing the issue. 

Btw will be there be any release soon with recent fixes?

**Comment by jovanlanik** [comment]
@vunnyso Yes, I plan to release v4.0.0 soonish.
