### ISSUE TITLE
GLib-GIO-CRITICAL: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

### ISSUE THREAD

**Issue by bound-variable** [jovanlanik/gtklock#102]
Not sure what to give the title...

My command works. But when I return to the terminal, this critical error message is displayed:

> (gtklock:17446): GLib-GIO-CRITICAL **: 15:09:10.914: g_dbus_connection_emit_signal: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

The command I run is:

`gtklock -L sus` where `sus` is this script:

```
#!/bin/bash --

# Suspend the machine


exec 9> /tmp/suspend.lock

flock --nonblock 9 || exit 1

echo shutdown >| /sys/power/disk
echo disk >| /sys/power/state
```

**Comment by jovanlanik** [comment]
I can only reproduce the issue when `DBUS_SESSION_BUS_ADDRESS` isn't set correctly.
Can you check if your dbus environment is correct?

**Comment by jovanlanik** [comment]
Closing as I don't think this is a gtklock issue.
