### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by aacebedo** [jovanlanik/gtklock#105]
There was several bug fixes since latest version and it would be great to have a new release. 
In addition NixOS release is approaching and thus the latest version would be integrated in the next release.

Would it be possible for you to add a new tag?

**Comment by aacebedo** [comment]
According to this https://github.com/NixOS/nixpkgs/issues/339153 I think 25th October.

**Comment by JohnRTitor** [comment]
Nope, actual release will be on November 22.

But major/breaking changes will have to be submitted by October 25.

If the package updates are backwards compatible, we can backport them after the October 25th window though.

**Comment by jovanlanik** [comment]
v4.0.0 is released
