### ISSUE TITLE
Display User Name when system is locked

### ISSUE THREAD

**Issue by vunnyso** [jovanlanik/gtklock#106]
Currently if not mistaken there is no way to find which user have logged in when system is locked using `Windows + L`.

If its possible to show user name as well above `Password` input it that will be beneficial for multi user environment as well. 

Good feature to add in :-)

**Comment by bhepple** [comment]
That's already available using gtklock-userinfo-module

**Comment by vunnyso** [comment]
Great, thanks @bhepple and @jovanlanik
