### ISSUE TITLE
After unlocking, fcitx5 can't enter non-English text to chromium.

### ISSUE THREAD

**Issue by knm100** [jovanlanik/gtklock#111]
After unlocking, fcitx5 can't enter non-English text in chromium, but can enter non-English text in other program.  if enter non-English text in thunderbird or restart fcitx5,  fcitx5 can enter non-English text in chromium again.
I don't know if this issue is caused by gtklock or by either chromuim or fcitx5.
if chang gtklock to  swaylock , everthing is going to ok.

**Comment by jovanlanik** [comment]
This is a pretty niche use case. I'm not sure if there is any easy way for me to test this.
Can you list all the software you are using and versions?
- gtklock version
- compositor and version
- fcitx5 version (and if you have any special configuration)
- chromium version

Also can you enter non-English text in gtklock?
Is only chromium having this issue?

**Comment by knm100** [comment]
gtklock ver:  gtklock4.0, gtklock-git-4.0.0.r9.g945313d 
compositor rev: labwc-git-0.8.1.r9.g2b877d22 (without xwayland)
chromium rev: chromium 130.0.6723.91 (wayland+text-input-v3)
fcitx5 rev: fcitx5 5.1.11+fcitx5-breeze 3.0.0+fcitx5-chinese-addons 5.1.7+fcitx5-configtool 5.1.7+fcitx5-qt  (with QT_IM_MODULE=fcitx)   no any special configuration.
DE Rev: LXQt 2.0(wayland session) on arch linux.

> Also can you enter non-English text in gtklock?

I can't enter non-English text in gtklock

> Is only chromium having this issue?

Yes, at least in the program I installed.( Qteminal, pcmanfm-qt,featherpad,audacious,thunderbird,libreoffice,cmake,kdiff3,nm-connection-editor)

by the way, if enter non-English text in nm-connection-editor,fcitx5 can enter non-English text in chromium again. I don't know if all GTK programs with non-English input can do this.

**Comment by jovanlanik** [comment]
Can you try running gtklock with `GTK_IM_MODULE="gtk-im-context-simple" gtklock`?

**Comment by knm100** [comment]
> Can you try running gtklock with `GTK_IM_MODULE="gtk-im-context-simple" gtklock`?

Running gtklock by this command will not affect chromium's non-English inputs.  I can enter non-English text to chromium after  
 unlocking

**Comment by knm100** [comment]
I have fcitx5 set to disallow fcitx5 in the password box, but after I set it to allow fcitx5 input in the password box, I can use fcitx5 to enter non-English text in gtklock, and I can also use fcitx5 to enter non-English text in chromium after unlocking. 
But after setting it up, it looks like I'm typing in a password box anywhere in chromium (Because I set the password box not to show the pre-edited text, so it will be very clear to see whether it is entered in the way of the password box)

**Comment by jovanlanik** [comment]
I think setting GTK_IM_MODULE is a good enough workaround for this issue, maybe I can add a config option to set it. I don't think the issue itself in gtklock.

**Comment by knm100** [comment]
I think so,    It's more likely a issue with chromium's Text-input protocol implementation

> maybe I can add a config option to set it

thank you, It's not necessary for me.   I will set it in bashrc and configuration file of the compositor.
