### ISSUE TITLE
somtime the gtklock need unlock three times to unlock the screen

### ISSUE THREAD

**Issue by knm100** [jovanlanik/gtklock#113]
I is using gtklock in labwc(wayland only)+lxqt,  the idle program is swayidle.  there is the following code in autostart file of labwc.
```
swayidle -w \
	timeout 300 'GTK_IM_MODULE="gtk-im-context-simple" gtklock' \
	timeout 600 'wlopm --off \*' \
	resume 'wlopm --on \*' \
	before-sleep 'GTK_IM_MODULE="gtk-im-context-simple" gtklock' >/dev/null 2>&1 &
	
	
```
when the wlopm have truned off the screen for a long time(I'm guessing more than half an hour),  the gtklock need unlock three times to unlock the screen.  the details are as follows
the first time: unlocked and showed the desktop then the gtklock quickly locked the screen by no more than half second.
the second time did the same as the first time
the third time unlocked the screen successfully.

I don't know if it's accidental, though I've encountered it twice in a row.

**Comment by jovanlanik** [comment]
Can you try running `gtklock & gtklock` in shell and report if it locks 2 times?

**Comment by knm100** [comment]
Locked only once, In the meantime, I haven't had this issue again.
![swappy-20241111-213750](https://github.com/user-attachments/assets/76bb116a-e41a-46c3-88a4-5a9e13bff599)

**Comment by jovanlanik** [comment]
Keep in mind if your are using `swayidle -w` you should use `gtklock -d`.

**Comment by knm100** [comment]
> Can you try running `gtklock & gtklock` in shell and report if it locks 2 times?

gtklock&&gtklock will lcoks 2 times.

>Keep in mind if your are using swayidle -w you should use gtklock -d.

I am useing `gtklock -d ` now,  haven't found anything wrong with it yet.

**Comment by knm100** [comment]
So I will close this issue for now
