### ISSUE TITLE
compilation error in fedora.

### ISSUE THREAD

**Issue by ldelossa** [jovanlanik/gtklock#12]
Hey,

I pulled in all the dependencies to do a local build of `gtklock`. When attempting to build I get a clang flag's error tho.

```
🖭  make
/usr/bin/clang   gtklock.o include/wlr-input-inhibitor-unstable-v1-client-protocol.h wlr-input-inhibitor-unstable-v1-client-protocol.o auth.o input-inhibitor.o module.o source.o window.o  -lpam -lwayland-client -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lgtk-layer-shell -lgmodule-2.0 -pthread -lglib-2.0  -o gtklock
clang-14: error: cannot specify -o when generating multiple output files
make: *** [<builtin>: gtklock] Error 1
```

Is this an issue with `makefile` or something on my end?

**Comment by jovanlanik** [comment]
Thank you for the report. This seems to be an issue with the makefile when using clang... I'll get to fixing it but in the meantime you cant try using gcc.

**Comment by ldelossa** [comment]
Thanks got it all working.

**Comment by jovanlanik** [comment]
I think I got it fixed so if you prefer clang you can try again.

**Comment by ldelossa** [comment]
Confirmed working with clang. Thanks a lot.
