### ISSUE TITLE
Wallpaper image with multiple monitors

### ISSUE THREAD

**Issue by ldelossa** [jovanlanik/gtklock#14]
When using a wallpaper image on the lock screen and then plugging in one or more monitors with different resolutions the image rendering on the external monitors does not take the size difference into account. This results in the image being stretched correctly on the laptop monitor, but does not stretch correctly on external monitors with larger resolutions.

**Comment by jovanlanik** [comment]
Can you provide the css you are using and a screenshot of what you mean by incorrect stretching?

**Comment by ldelossa** [comment]
Here is CSS:

```
window {
   background-image: url("/home/louis/Dropbox/Wallpapers/minimalist-landscape-4k-jt-2560x1600-orange.jpg");
   background-size: contain;
   background-repeat: no-repeat;
   background-position: center;
   background-color: #31455b;
}
```
I cannot take a screenshot since the screen is locked but here is a photo:
![image](https://user-images.githubusercontent.com/5642902/172952297-d763d50e-21d6-4663-9838-f72dd85abbd1.png)

**Comment by ErikReider** [comment]
@jovanlanik I've messed around with drawing wallpapers on different monitors with GTK the past few days and it seems to work better if cairo is used instead of CSS. 

Here's a working example written in Vala
[Example](https://github.com/ErikReider/SwaySettings/pull/35)

**Comment by jovanlanik** [comment]
> Here is CSS:
> 
> ```
> window {
>    background-image: url("/home/louis/Dropbox/Wallpapers/minimalist-landscape-4k-jt-2560x1600-orange.jpg");
>    background-size: contain;
>    background-repeat: no-repeat;
>    background-position: center;
>    background-color: #31455b;
> }
> ```

Try setting background-size to cover. Maybe the real issue is my documentation... I have a false assumption everyone is familiar with css. I'll work to document gtklock better.

**Comment by ldelossa** [comment]
That did it, thanks!

**Comment by jovanlanik** [comment]
> @jovanlanik I've messed around with drawing wallpapers on different monitors with GTK the past few days and it seems to work better if cairo is used instead of CSS. 
> 
> Here's a working example written in Vala
> [Example](https://github.com/ErikReider/SwaySettings/pull/35)
> 
> Edit: the relevant bits are in the src/wallpaper directory :)

Any advantages to this approach?

**Comment by ldelossa** [comment]
One other quick question. Is there a CSS class for the text on the lock screen? I use a theme switcher which swaps out GTK settings. The text color seems to swap with my GTK light/dark settings. I'd like to avoid this since I use the same background for lock screen regardless.

**Comment by ErikReider** [comment]
> Any advantages to this approach?

A few but probably not needed for this project now that this issue is fixed. The only advantages are manual control over scaling and rendering and no need for it to be included in a CSS file. I wonder if that's how gtk renders the images in the backend?

**Comment by jovanlanik** [comment]
> One other quick question. Is there a CSS class for the text on the lock screen? I use a theme switcher which swaps out GTK settings. The text color seems to swap with my GTK light/dark settings. I'd like to avoid this since I use the same background for lock screen regardless.
The selector `label` works fine but it does change the color of the text in the button too.

**Comment by jovanlanik** [comment]
> > Any advantages to this approach?
> 
> A few but probably not needed for this project now that this issue is fixed. The only advantages are manual control over scaling and rendering and no need for it to be included in a CSS file. I wonder if that's how gtk renders the images in the backend?
> 
> 
I really like CSS because it's a no-code solution. GTK does all the work and offers many scaling options and even a fallback color if the image fails to load.

**Comment by ldelossa** [comment]
> > One other quick question. Is there a CSS class for the text on the lock screen? I use a theme switcher which swaps out GTK settings. The text color seems to swap with my GTK light/dark settings. I'd like to avoid this since I use the same background for lock screen regardless.
> 
> The selector `label` works fine but it does change the color of the text in the button too.

works like a charm, changing color on button still looks fine :+1:

**Comment by jovanlanik** [comment]
@ldelossa I added some names to various widgets in master. The new selector would be `#clock-label, #input-label` if you don't want to change the button.

**Comment by ldelossa** [comment]
Awesome. Thanks
