### ISSUE TITLE
Long pause unlocking after resume

### ISSUE THREAD

**Issue by ldelossa** [jovanlanik/gtklock#15]
Hey,

Not a great bug report here since it seems pretty intermittent but have you noticed very long pause on unlock after resume? At first I thought gtklock crashed as it got stuck on the spinner. Then I let it sit for awhile and it actually did finish.

**Comment by ldelossa** [comment]
Actually, its occurring every time in my current session. Lmk if you want any debug info. It could be the fprint pam module stuff as well?

**Comment by ldelossa** [comment]
Sorry, my own fault, I keep forgetting "make install" will copy over the default pam file. Replaced it with the fprint one and things work fine again.

**Comment by jovanlanik** [comment]
Seems like an oversight to me. I'll add a check to the makefile if the file already exists.

**Comment by jovanlanik** [comment]
I did something different, I added 2 targets `install-bin` and `install-data` to the makefile, if you want to keep your config use `install-bin`. Using the normal `install` target will do both.
