### ISSUE TITLE
How to use 12-hour time?

### ISSUE THREAD

**Issue by yavko** [jovanlanik/gtklock#20]

**Comment by jovanlanik** [comment]
I added support for custom time formats in master...
Either launch with `$ gtklock -t '%I:%M %p'` or add this to ~/.config/gtklock/config.ini:
```ini
[main]
time-format=%I:%M %p
```
The format is the same as the date command, see `$ man date` for details. A few examples are `%X` (locale default with seconds), `%c` (locale default with date), `%I:%M` (12-hour withour AM or PM) or `%R` (24-hour gtklock default).

**Comment by yavko** [comment]
> I added support for custom time formats in master... Either launch with `$ gtklock -t '%I:%M %p'` or add this to ~/.config/gtklock/config.ini:
> 
> ```ini
> [main]
> time-format=%I:%M %p
> ```
> 
> The format is the same as the date command, see `$ man date` for details. A few examples are `%X` (locale default with seconds), `%c` (locale default with date), `%I:%M` (12-hour withour AM or PM) or `%R` (24-hour gtklock default).

Thanks!
