### ISSUE TITLE
initially hide the form when the `-b`ackground image used

### ISSUE THREAD

**Issue by nwg-piotr** [jovanlanik/gtklock#21]
Thank you for adding the `-b` flag. It looks superb.

I think it would look even better if the clock, the password label and the unlock button were initially hidden, and show up on a key or button event.

Thank you for your work, it goes well with what I'm working on.

**Comment by jovanlanik** [comment]
I'll try implementing your suggestion soon. I think I'll a new option for this...

I'm glad you find gtklock useful, I use your nwg-shell and love it 😄.

**Comment by nwg-piotr** [comment]
Excellent news, thank you!

I'm working on the 'Idle & Lock screen' settings. Swaylock and gtklock will be two lockers to choose from.

![image](https://user-images.githubusercontent.com/20579136/177650730-aba61925-b87b-4687-8f16-e2551f0b9fdc.png)

**Comment by nwg-piotr** [comment]
> I think it would look even better if the clock, the password label and the unlock button were initially hidden

Or maybe just the clock visible? It looks good on almost any background.

**Comment by nwg-piotr** [comment]
Hey, doesn't it look cool? :)

![2022-07-13-113912_screenshot](https://user-images.githubusercontent.com/20579136/178704659-983623ca-a077-461c-82d2-a7b7bc658405.png)

**Comment by jovanlanik** [comment]
I added this feature and a few options for it (`idle-hide`, `idle-timeout`, `start-hidden`).
It needs testing but seems to work well for me.

**Comment by nwg-piotr** [comment]
> seems to work well for me

Same here. I'll put off nwg-shell-config release to wait for the new gtklock.

**Comment by jovanlanik** [comment]
Well, it's been a few days and I still had no issues. I'll close the issue and push out a release soon.
