### ISSUE TITLE
gtklock not working when compiled using musl

### ISSUE THREAD

**Issue by rbragadeandrade** [jovanlanik/gtklock#24]
When compiling gtklock in musl based distros (i'm using Alpine), after typing the password to unlock there is a infinite loading which never ends.

Following message is displayed at dmesg command:

[ 1696.746924] gtklock[28089]: segfault at 0 ip 00007f18ee42c6b9 sp 00007f18ea0fde18 error 6 in ld-musl-x86_64.so.1[7f18ee3f0000+48000]

**Comment by jovanlanik** [comment]
I think I fixed it in master, can you confirm? I'll do some testing once I have access to my musl vm.
