### ISSUE TITLE
account locked for no reason

### ISSUE THREAD

**Issue by nwg-piotr** [jovanlanik/gtklock#26]
This happens to me on the random basis:

![image](https://user-images.githubusercontent.com/20579136/182980052-c7bbcae0-2818-4e93-aab2-3de4b38f030b.png)

Last night and 4 times tonight, out of nowhere, I had my account blocked for 10 minutes. I was playing with changing user images, using in turns mugshot and swaysettings, and also deleting images manually. No idea if it matters. I remember having a similar incident at the office, on some older gtklock version. I'm pretty sure I entered my password correctly every time, and 100% sure that I couldn't misspell it 3 times.

```text
$ gtklock -i -m userinfo-module

** (gtklock:280886): WARNING **: 02:53:06.671: gtk-layer-shell v0.7.0 may not work on GTK v3.24.34. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md

(gtklock:280886): GLib-CRITICAL **: 02:53:06.703: g_key_file_load_from_file: assertion 'file != NULL' failed

(gtklock:280886): GLib-GObject-CRITICAL **: 03:03:05.260: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

Both `~/.face` and `/var/lib/AccountsService/icons/piotr` are present at the moment.

**Comment by jovanlanik** [comment]
I'm not sure this is a gtklock issue but it's possible that gtklock does something wrong in the PAM conversation function...
Using the userinfo module shouldn't be relevant. What distro are you on? Do you have any unusual PAM configuration?

**Comment by nwg-piotr** [comment]
> What distro are you on?

Arch Linux

> Do you have any unusual PAM configuration?

Basic, [probably](https://wiki.archlinux.org/title/PAM#Installation). I had to ask Google what PAM means.

**Comment by jovanlanik** [comment]
Can you check for a logged occurrence? If you check using `$  journalctl --user`, there should be a message similar to:
```
Aug 08 17:50:41 arch gtklock[659]: pam_unix(gtklock:auth): authentication failure; logname= uid=1000 euid=1000 tty= ruser= rhost=  user=lanikjo
```
and for `$ jorunalctl --system` there should be something like:
```
Aug 08 17:49:48 arch audit[546]: USER_AUTH pid=546 uid=1000 auid=1000 ses=4 msg='op=PAM:unix_chkpwd acct="lanikjo" exe="/usr/bin/unix_chkpwd" hostname=? addr=? terminal=? res=failed'
Aug 08 17:49:48 arch kernel: audit: type=1100 audit(1659980988.655:92): pid=546 uid=1000 auid=1000 ses=4 msg='op=PAM:unix_chkpwd acct="lanikjo" exe="/usr/bin/unix_chkpwd" hostname=? addr=? terminal=? res=failed'
```

**Comment by nwg-piotr** [comment]
Sorry, I'm by the lake with only my old testing lappy. I'll be back in the business next week.

**Comment by jovanlanik** [comment]
No problem, enjoy your vacation 😄

**Comment by dit7ya** [comment]
I am trying to get this packaged for NixOS but seems like my passwords just don't work with the produced binary?

I am getting errors like the following

```console

 pam_warn(gtklock:auth): function=[pam_sm_authenticate] flags=0 service=[gtklock] terminal=[<unknown>] user=[dit7ya] ruser=[<unnown>] rhost=[<unknown>]
 
 pam_warn(gtklock:setcred): function=[pam_sm_setcred] flags=0x10 service=[gtklock] terminal=[<unknown>] user=[dit7ya] ruser=[<unknown>] rhost=[<unknown>]
 
 ```
 
 Any clues?

**Comment by jovanlanik** [comment]
Yes, the install step is required or PAM won't authenticate you. I don't know where PAM config files are located in nixOS but on other distros it's `/etc/pam.d`

**Comment by dit7ya** [comment]
Thanks. I figured something out and opened a PR for packaging it intohttps://github.com/NixOS/nixpkgs/pull/186055

**Comment by nwg-piotr** [comment]
> Can you check for a logged occurrence?

For both queries I have just one occurrence dated 5th Aug. This might've been a really misspelled password.

```text
$ journalctl --user | grep 'authentication failure'

sie 05 01:21:54 msi gtklock[92990]: pam_unix(gtklock:auth): authentication failure; logname= uid=1000 euid=1000 tty= ruser= rhost=  user=piotr

$ journalctl --system | grep 'exe="/usr/bin/unix_chkpwd" hostname=? addr=? terminal=? res=failed'

sie 05 01:21:54 msi audit[92992]: USER_AUTH pid=92992 uid=1000 auid=1000 ses=1 msg='op=PAM:unix_chkpwd acct="piotr" exe="/usr/bin/unix_chkpwd" hostname=? addr=? terminal=? res=failed'
sie 05 01:21:54 msi kernel: audit: type=1100 audit(1659655314.176:259): pid=92992 uid=1000 auid=1000 ses=1 msg='op=PAM:unix_chkpwd acct="piotr" exe="/usr/bin/unix_chkpwd" hostname=? addr=? terminal=? res=failed'
```

**Comment by jovanlanik** [comment]
Okay, I think I'd be best to leave the issue open for a little while or until you get another occurrence.
If you don't want gtklock to lock your account after failure I can help you configure PAM to disable the `pam_faillock` module either system-wide or only for gtklock.

**Comment by nwg-piotr** [comment]
Well, we don't really need a solution on my machine, but anywhere. Yes, let's leave it open for further testing. I'll check journalctl if/when it happens again.

**Comment by jovanlanik** [comment]
What I meant is, if it turns out to be a misspelled pw and not a gtklock issue, you could avoid it that way. If it's a bug, it should be fixed.

**Comment by nwg-piotr** [comment]
My `/etc/security/faillock.conf` is 100% default (all lines commented out). Does gtklock need changes in it?

**Comment by jovanlanik** [comment]
No, gtklock should work with default PAM and faillock configs on arch.

**Comment by nwg-piotr** [comment]
No, but I only used gtklock w/o the userinfo module so far. Just added the module support in the latest nwg-shell-config, so it's going to be used on the daily basis, at least on my machines. We will see.

**Comment by nwg-piotr** [comment]
I've been testing for a week now, nothing bad happened. Closing. Will re-open if something goes wrong.

**Comment by nwg-piotr** [comment]
It happened tonight, after changing the avatar with mughshot. Dunno if it matters.

![image](https://user-images.githubusercontent.com/20579136/190535155-82211a16-6383-4051-b6bf-a5c5e9ef7eb5.png)

[journalctl-user](https://gist.github.com/nwg-piotr/15512da5deecfebce5f27d12bbe3d0f5)

[journalctl-system](https://gist.github.com/nwg-piotr/7783b5c59ec6575d6d0da8239fdcb3c9)

**Comment by nwg-piotr** [comment]
I'm still unsure, but it seems as if mistyped passwords accumulated in some way over time after startup. Maybe it's not gtklock's fault. Closing again. :rofl:
