### ISSUE TITLE
No capslock warning

### ISSUE THREAD

**Issue by emanuelserpa** [jovanlanik/gtklock#35]
When the capslock is activated, gtklock doesn't warn the user that the capslock is activated.

Thanks for this program!

**Comment by jovanlanik** [comment]
GTK does support this (https://docs.gtk.org/gtk3/property.Entry.caps-lock-warning.html) but gtklock uses the secondary icon for the password visibility toggle. Any suggestions where in the UI to implement the warning?

**Comment by emanuelserpa** [comment]
Tried to see how gdm does here, but it doesn't work somehow.

But what about showing a text below the password entry?

![image](https://user-images.githubusercontent.com/934124/188761999-9e83e98e-a377-4c96-a8d2-2bedd45d9ec5.png)

**Comment by jovanlanik** [comment]
Added in e640f5c9c5f743a5beb84dddcf786e00ba1646ec.

**Comment by emanuelserpa** [comment]
Perfect! Thank you!
