### ISSUE TITLE
Support Yubikey Challenge Response Login

### ISSUE THREAD

**Issue by ldelossa** [jovanlanik/gtklock#36]
Attempting this in my gtklock pam file:

```
auth            sufficient      pam_yubico.so mode=challenge-response chalresp_path=/etc/yubico
```

https://developers.yubico.com/yubico-pam/Authentication_Using_Challenge-Response.html

This currently works in sudo pam file. However, gtklock seems to always report login failed if this is present. 

You can add a debug flag to the pam module options, to try to determine why it failed, but this causes gtklock to segfault.

**Comment by ldelossa** [comment]
nvm, this was because challenge file was owned by root, locked it down to just root and my user (who runs gtklock in sway's instance)/

**Comment by jovanlanik** [comment]
> Tho, I guess you may want to handle gtklock seg faulting with a pam module in debug, but w/e not a big deal since it all works

Does gtklock completely fail in this case or only the auth child?

**Comment by ldelossa** [comment]
Seems like the whole UI fails. Tho, actually, i was attempting this when perms were bad. Let me try putting debug back, now that things are working

**Comment by ldelossa** [comment]
Yup, it was just a perms issue. Things work fine. Tho gtk doesnt seem to forward the pam debug logs to stdout. Prob not the same stream the pam messages get written to?

**Comment by jovanlanik** [comment]
I'll see what I can do about pam output...

**Comment by ldelossa** [comment]
Yup, tbh, its not a huge deal since you can just put debug on the cli for testing, outside of gtklock and make sure things work. But could be handy.

**Comment by jovanlanik** [comment]
Can you test if this works for you now?
