### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jovanlanik** [jovanlanik/gtklock#4]
After entering a wrong password and pressing random keys the program crashes.
Discovered by reddit user [here](https://www.reddit.com/r/linux/comments/ushd6j/comment/i94z9e0/?utm_source=share&utm_medium=web2x&context=3).

**Comment by jovanlanik** [comment]
Can you open a new issue? Seems to have a completely different cause than what was described in this issue.
Also some info about your system would be useful, like your distro and versions of relevant packages.

**Comment by p00f** [comment]
#9
