### ISSUE TITLE
Port to gtk4

### ISSUE THREAD

**Issue by ghost** [jovanlanik/gtklock#44]

**Comment by jovanlanik** [comment]
Not really possible at the moment...
There is not support in gtk4 for custom wayland surfaces and without it I can't implement wlr-layer-shell or ext-session-lock.
See https://github.com/wmww/gtk-layer-shell/issues/37, https://gitlab.gnome.org/GNOME/gtk/-/issues/2132 and https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/2992.

**Comment by jovanlanik** [comment]
Might be possible now that gtk4-layer-shell is out.

**Comment by jovanlanik** [comment]
Work started on the gtk4 branch. Doesn't compile at the moment.

**Comment by jovanlanik** [comment]
Lockscreens using the layer-shell protocol are unsafe and gtk-session-lock is gtk3 only. Closing as not planned.
