### ISSUE TITLE
[Feature request] User Switching

### ISSUE THREAD

**Issue by lepz0r** [jovanlanik/gtklock#45]
Add a button to execute a command to switch to Display Manager like `gdmflexiserver` for GDM or `dm-tool switch-to-greeter` for LightDM

**Comment by jovanlanik** [comment]
Certainly possible, although maybe I'd implement it as a part of gtklock-powebar module...

**Comment by jovanlanik** [comment]
I added a button to [gtklock-powerbar-module v2.0.0](https://github.com/jovanlanik/gtklock-powerbar-module/releases/tag/v2.0.0).
Set the `userswitch-command` option to `gdmflexiserver` (or any other command) to enable the button.

**Comment by lepz0r** [comment]
thx jovanlanik/gtklock-powerbar-module@ec8488a2d46d346faa2ee0a317985afefa9c9de5
