### ISSUE TITLE
Feature Request: Allow positioning window-box

### ISSUE THREAD

**Issue by cinerea0** [jovanlanik/gtklock#47]
Currently the window box is always placed in the center of the screen. I think it would be useful to be able to position the box at the top or bottom of the screen. I did some examination of GTK's CSS properties, and I was unable to find a way to move the box around.

**Comment by jovanlanik** [comment]
I honestly don't see the point of moving the box from the center... Is there any practical reason or a specific style you're trying to achieve?

I'm not opposed to implementing it even if there's no explanation but I'm just curious.

**Comment by cinerea0** [comment]
I asked this because the image background on my lock screen is very "busy" toward the center, so the text on top of it could be hard to make out. My thinking was that I could fix this problem if I could move the box away from the center. I had forgotten that I could just add a half-transparent background to the box, which fixes the problem just as well. Since the problem has been resolved with the current feature set, there is no need for this issue to remain open.
