### ISSUE TITLE
[FEATURE REQUEST]: Still execute unlock command when gtklock receives signal

### ISSUE THREAD

**Issue by jasyip** [jovanlanik/gtklock#51]
It would be nice if gtklock can still execute the unlock command upon receiving a signal intended to terminate gtklock. Maybe it could be SIGINT, SIGTERM, or SIGUSR+something.

This is an awesome tool by the way!

**Comment by jovanlanik** [comment]
Thank you for the kind words.

I have no issue implementing this but I am curious about the use case.
Why do you want to kill gtklock before authentication?

**Comment by jovanlanik** [comment]
Okay thanks. I'll have a look at it when I have time.

**Comment by jovanlanik** [comment]
gtklock should now execute the unlock command when killed by SIGTERM.
