### ISSUE TITLE
[Feature Request] Add keyboard layout display

### ISSUE THREAD

**Issue by maksalees** [jovanlanik/gtklock#55]
When several keyboard layouts are set, it can be difficult to enter a password because the selected layout is not displayed.

**Comment by jovanlanik** [comment]
I looked into it and couldn't find a standard way to get the layout in wayland. I don't want to implement compositor specific features into gtklock. What compositor are you using?

**Comment by maksalees** [comment]
> I looked into it and couldn't find a standard way to get the layout in wayland. I don't want to implement compositor specific features into gtklock. What compositor are you using?

Sway. This feature is in swaylock. Does it use the compositor specific features for this?

**Comment by jovanlanik** [comment]
I'll check out what swaylock does...

**Comment by jovanlanik** [comment]
Unfortunately, swaylock can listen for wl_keyboard events (specificaly [keymap](https://wayland.app/protocols/wayland#wl_keyboard:event:keymap)). I can't use because gtk already listens to them. gtk4 has a function for this use case ([gdk_wayland_device_get_xkb_keymap](https://docs.gtk.org/gdk4-wayland/method.WaylandDevice.get_xkb_keymap.html)) but there is no gtk3 equivalent.

**Comment by maksalees** [comment]
> Unfortunately, swaylock can listen for wl_keyboard events (specificaly [keymap](https://wayland.app/protocols/wayland#wl_keyboard:event:keymap)). I can't use because gtk already listens to them. gtk4 has a function for this use case ([gdk_wayland_device_get_xkb_keymap](https://docs.gtk.org/gdk4-wayland/method.WaylandDevice.get_xkb_keymap.html)) but there is no gtk3 equivalent.

Will gtklock be ported to gtk4?

**Comment by jovanlanik** [comment]
See #44.

**Comment by ildar** [comment]
I believe with Hyprland it's possible through the remote control utility (hyprctl). Can you guys make a widget for it? Thanks.

**Comment by jovanlanik** [comment]
I've given up on porting to gtk4 for now and this feature isn't possible on gtk3 so closing.

**Comment by Ty3uK** [comment]
> I believe with Hyprland it's possible through the remote control utility (hyprctl). Can you guys make a widget for it? Thanks.

If you don't mind check [this one](https://github.com/Ty3uK/gtklock-xkb-layout-module), please.

Just finished, it covers my use cases, feedback will be much appreciated. 🙂
