### ISSUE TITLE
Support multiple modules

### ISSUE THREAD

**Issue by bhepple** [jovanlanik/gtklock#56]
How to support multiple modules in the config.ini file?

With this:

```
[main]
modules=userinfo-module.so
modules=playerctl-module.so
modules=powerbar-module.so
```

... only the final module is loaded

These fail completely:

```
modules=a,b,c
modules=a b c
```

This works fine:
```
LD_LIBRARY_PATH=/usr/local/lib/gtklock gtklock -m powerbar-module -m userinfo-module -m playerctl-module
```

**Comment by jovanlanik** [comment]
try `modules=a;b;c`

**Comment by jovanlanik** [comment]
To clarify why, gtklock uses key file (https://developer-old.gnome.org/glib/unstable/glib-Key-value-file-parser.html). The syntax is the same as desktop files.

**Comment by bhepple** [comment]
Ah, sweet! Thanks.
