### ISSUE TITLE
Lock occurs after a delay (25 seconds) instead of immediately

### ISSUE THREAD

**Issue by jordan-bravo** [jovanlanik/gtklock#57]
### Expected behavior
Running the command `gtklock` should immediately lock the screen.

### Actual behavior
Running the command `gtklock` waits 25 seconds, then locks the screen.

### Steps to reproduce
1. Install `gtklock` on NixOS.
2. Add necessary setting `security.pam.services.gtklock = {};`.
3. Run command `gtklock`.

System info:
Operating System: NixOS (x86_64)
Wayland Compositor / Window Manager: Hyprland
Terminal: Kitty
Display Manager: GDM

Please let me know if there's any other info that would be helpful.

**Comment by jovanlanik** [comment]
Which gtklock version are you using (and has a previous version worked for you)? Do you use `--daemonize`?

**Comment by jordan-bravo** [comment]
> Which gtklock version are you using (and has a previous version worked for you)?

I'm using the [NixOS package](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=gtklock).

>  Do you use `--daemonize`?

I've tried both `swaylock` and `swaylock -d`, same result.  Every time it delays for 25 seconds before locking.

**Comment by jordan-bravo** [comment]
Excuse the typo in my previous reply.  I meant to type that I have tried both commands `gtklock` and `gtklock -d` and it has the same result, delays for 25 seconds before locking.

**Comment by niksingh710** [comment]
on Arch linux feeling some delay not 25 seconds but for a few seconds 
`version: v2.1.0`
it is of a few milliseconds in which it is possible to execute any command if terminal is open

**Comment by jordan-bravo** [comment]
I saw reports of users experiencing the "delay" issue and attributing the problem to an issue with the the Hyprland custom Wayland portal not being configured correctly.

I have not been able to solve the issue so far but if anyone else is experiencing this, please comment for visibility.

**Comment by niksingh710** [comment]
> I saw reports of users experiencing this "delay" issue and attributing the problem to an issue with the the Hyprland custom Wayland portal not being configured correctly.
> 
> I have not been able to solve the issue so far but if anyone else is experiencing this, please comment for visibility.

is this only happening in Hyprland ? i am using Hyprland and seems to happen for me.

**Comment by niksingh710** [comment]
> Had this issue before, it's not unique to hyprland. You must start an instance of XDG Desktop Portal, otherwise most of GTK applications will take 25 seconds to start

i have instance of xdg-portal running 
for me it is not 25 seconds but the time gap between the lock command is issued and the lock is displayed is enough to perform a action in between that.

**Comment by mdeboer** [comment]
Make sure you have only one xdg-portal installed and that it's the correct one (either hyprland or wlr). Also see [here](https://wiki.archlinux.org/title/XDG_Desktop_Portal) and [here](https://wiki.archlinux.org/title/XDG_Desktop_Portal).
