### ISSUE TITLE
[Feature request] Add layout config

### ISSUE THREAD

**Issue by Lassebq** [jovanlanik/gtklock#58]
Instead of hardcoding all of the elements, I think there could be something like an html or xml with the layout.
Afaik gtk only supports css, but at least add some way to customize it instead of hardcoding.
Max I was able to do with css is hide the "Password" label by making font size 0.
I still want to get rid of unlock button, or at least make it centered.
<img src="https://github.com/jovanlanik/gtklock/assets/68742864/ded2e15c-d510-44dc-8b0b-6ff46043753b" width="60%"/>

**Comment by jovanlanik** [comment]
The UI isn't hardcoded anymore... It's loaded from a gresource that is built using the gtklock.ui xml file (https://github.com/jovanlanik/gtklock/blob/master/res/gtklock.ui). Should be possible to load an alternative xml file at runtime.

**Comment by Lassebq** [comment]
Oh, there is no way to set it with a parameter though, is there?

**Comment by jovanlanik** [comment]
> Oh, there is no way to set it with a parameter though, is there?

Not yet, I'll be working on this feature. The UI xml file can also be edited in Glade 3.

> Oh, and while we're on topic of configuration, I wanted to mention that config.ini interprets `~` as literal string instead of user home. env variables don't work either

Intended behaviour. I don't really think it's worth the time it would take to implement. I am open to merging a PR if someone were to do it...

**Comment by jovanlanik** [comment]
GtkBuilder constructs the UI at runtime from a resource compiled at build time. The resource is a linkable object file containing the content of the xml file.

**Comment by jovanlanik** [comment]
@Lassebq Should work in master. You can try playing around with gtklock.ui in glade but be carefull not to delete widgets or change names. A missing widget could cause a warning, error or crash... Also modules won't work with this feature until they get updated.

**Comment by Lassebq** [comment]
Oh huh, with master build I can now see visibility toggle. It wasn't in the aur build for some reason

**Comment by Lassebq** [comment]
![image](https://github.com/jovanlanik/gtklock/assets/68742864/78abd284-4dcb-4823-b7f4-64ec51891b77)
Great! Closing the issue as completed.
