### ISSUE TITLE
Crash when disabling display

### ISSUE THREAD

**Issue by trbjo** [jovanlanik/gtklock#6]
If you disable a display, for example when you connect your laptop to an external display, gtklock will crash, leaving the session unlocked.

How to reproduce:
Run `gtklock &!; sleep 2; swaymsg output eDP-1 disable; sleep 2; swaymsg output eDP-1 enable`

**Comment by jovanlanik** [comment]
Can't seem to reproduce... Maybe you could give me more info? What distro are on? Are you using a package or building gtklock yourself? Versions of sway and all libraries (gtk3, gtk-layer-shell, wayland, pam)?

Maybe try logging the crash in gdb and send me the output.

**Comment by trbjo** [comment]
Arch linux, just built it using make and make install. Will debug later and post the output here. 
- `local/gtk3 1:3.24.34-1`
- `sway version 1.8-dev-b20585b2 (Apr 23 2022, branch 'HEAD')`
- `local/gtk-layer-shell 0.7.0-2`
- `local/wlroots-git 0.16.0.r5457.640f3b9f-1`

**Comment by jovanlanik** [comment]
Okay, I'll try replicating in my arch vm.

**Comment by jovanlanik** [comment]
Also check out the AUR package, if you don't want to compile gtklock manually.
https://aur.archlinux.org/packages/gtklock-git

**Comment by jovanlanik** [comment]
@trbjo Any info on this? I can't reproduce...

**Comment by jovanlanik** [comment]
I think 20a5b4d2caa8ce890e454655289336058e71fc56 fixed this, can you confirm?
