### ISSUE TITLE
Password box not focused when screen is locked

### ISSUE THREAD

**Issue by MonstrousOgre** [jovanlanik/gtklock#60]
When gtklock starts, the box where I type the password is not focused. I just have to move my mouse a bit for it to get focused, but I'd rather be able to type without having to move my mouse first.

This wasn't happening a week ago. The textbox used to be focused right away, but something changed after I moved to a new location, even though my setup is nearly identical.

If it makes a difference, I'm using a laptop with an external monitor.

**Comment by MonstrousOgre** [comment]
Update: It's focused if I disconnect my external monitor and use only my laptop display. But earlier it was working fine even when I used it with the external monitor.

**Comment by cafetestrest** [comment]
I've experience the same thing, just I'm using PC so unsure if the external monitor applies to me.
Gets kinda annoying when I start typing password but the field won't focus unless I move my mouse a bit.

**Comment by cafetestrest** [comment]
Hi @jovanlanik ,
I'm not that familiar with GTK, just seen that the GtkEntry can have gtk_entry_grab_focus_without_selecting from https://docs.gtk.org/gtk3/method.Entry.grab_focus_without_selecting.html
Can this be used to resolve this issue?
Thank you for your time.

**Comment by Lassebq** [comment]
I can confirm that the whole wlr layer shell doesn't get focused, since some keys go through the layer to the previously active window

**Comment by Lassebq** [comment]
So I assume the issue is not with the text box, but with the layer itself

**Comment by cafetestrest** [comment]
@Lassebq ,
Yes, you are correct. I was able to verify it today. I run the systemctl suspend and it was still focused on my terminal, in which I was able to run pkill gtklock and thus enter without entering the password (I'm running Hyprland).

The way I was able to mitigate the problem is by running gtklock -d && sleep 1 && systemctl suspend, then when the PC is resumed from sleep, the password box is focused properly, which for some reason isn't the case when resuming from sleep on it's own.

**Comment by jovanlanik** [comment]
@cafetestrest Can you test the current master?

**Comment by jovanlanik** [comment]
@MonstrousOgre @Lassebq Do you only have this issue when using the daemonize option and suspending the device?

**Comment by cafetestrest** [comment]
> @cafetestrest Can you test the current master?

HI @jovanlanik ,
Somewhat better now, I'm unable to replicate it everytime now, but I was able to get it to happen again, where the terminal was still focused and I was able to kill gtklock.
So still not resolved fully.

The way I'm replicating it is from within another program called ags, that is basically my topbar and that is calling the scipt that calls systemctl suspend.

**Comment by MonstrousOgre** [comment]
Sorry for the late reply
> @Lassebq , Yes, you are correct. I was able to verify it today. I run the systemctl suspend and it was still focused on my terminal, in which I was able to run pkill gtklock and thus enter without entering the password (I'm running Hyprland).
> 
> The way I was able to mitigate the problem is by running gtklock -d && sleep 1 && systemctl suspend, then when the PC is resumed from sleep, the password box is focused properly, which for some reason isn't the case when resuming from sleep on it's own.

I'm still on v2.1.0 but I'm not having this issue since it's not forwarding the keys to the window. It appears to be just the textbox for me that's not getting focused.

**Comment by MonstrousOgre** [comment]
@jovanlanik it's happening even with master

**Comment by jovanlanik** [comment]
Can you try with #88?
