### ISSUE TITLE
Need void packages for modules

### ISSUE THREAD

**Issue by bhepple** [jovanlanik/gtklock#66]
I've made a stab at them here:

[userinfo](https://github.com/bhepple/void-packages/blob/gtklock-userinfo-module/srcpkgs/gtklock-userinfo-module/template)
[powerbar](https://github.com/bhepple/void-packages/blob/gtklock-powerbar-module/srcpkgs/gtklock-powerbar-module/template)
[playerctl](https://github.com/bhepple/void-packages/blob/gtklock-playerctl-module/srcpkgs/gtklock-playerctl-module/template)
[runshell](https://github.com/bhepple/void-packages/blob/gtklock-runshell-module/srcpkgs/gtklock-runshell-module/template)
[countdown](https://github.com/bhepple/void-packages/blob/gtklock-countdown-module/srcpkgs/gtklock-countdown-module/template)

They all seem to work OK on my system.

Feel free to snarf them and put up on void-packages :-) (I don't have push rights there)

**Comment by jovanlanik** [comment]
Thank you! I'll try building once I have time. I don't have push rights either but maybe I can submit a PR.
