### ISSUE TITLE
swww autoexec pointing to wrong wallpaper in config (m3ww)

### ISSUE THREAD

**Issue by MyLiege23** [jovanlanik/gtklock#67]
Hi there, I just noticed that eww saves the wallpaper to `~/.config/eww/images/wallpaper` and in the execs.conf, the wallpaper is trying to open `~/.config/eww/images/wallpaper/wallpaper` 

Just letting you know. Every boot, I was getting a blank screen as a wallpaper, then I'd set it again manually.

**Comment by MyLiege23** [comment]
Actually, again on boot, I still get a black background for my wallpaper on boot. Is this a config issue, eww issue, or a swww issue? any idea? 

I'll look more into it and edit this comment to update any findings.

**Comment by jovanlanik** [comment]
I'm not sure what swww is. If you need to set a wallpaper in gtklock use `$ gtklock -b /path/to/image.png` or in the config file set:
```
[main]
background=/path/to/image.png
```

**Comment by MyLiege23** [comment]
I am so sorry - I had many GitHub repos open, and I posted an issue on the wrong page! You can completely ignore this!
