### ISSUE TITLE
Lockscreen can be bypassed when plugging/unplugging a monitor. 

### ISSUE THREAD

**Issue by RoccoRakete** [jovanlanik/gtklock#70]
This seems to be a security issue, since when ever I plug or unplug a monitor, the PC isn't locked anymore. Are there logfiles to track down this issue?

**Comment by BurnyLlama** [comment]
I have the same issue when using dpms to turn off my monitor screen after a while...

**Comment by jovanlanik** [comment]
Should be fixed by #88.
