### ISSUE TITLE
Reliably coredumps when using fingerprint

### ISSUE THREAD

**Issue by Jackaed** [jovanlanik/gtklock#72]
Using latest HEAD gtklock reliably coredumps if I attempt to login by using my fingerprint but using the wrong finger to make it fail the authentication. Possibly related to #40.

**Comment by Jackaed** [comment]
So far, I have had luck with both Swaylock and (what I'm currently using) Hyprlock. The conversation [here](https://github.com/hyprwm/hyprlock/issues/258#issuecomment-2074801187) may be relevant for you.

**Comment by tv42** [comment]
I trigger this way too often when I have worn/callused/wet fingertips and run out of tries. The screen goes red and gtklock is no more.

For anyone else stumbling on this, to recover from the (very useful!) `ext-session-lock-v1` lockout, you can

- switch to a different console: ctrl-alt-f2
- log in there
- run gtklock again: `WAYLAND_DISPLAY=wayland-1 exec gtklock` (that'll log out of tty2 automatically as soon as you unlock)
- now your wayland session is "normally locked", out of the red screen
- switch to it with alt-f1, and try logging in again

**Comment by mochaaP** [comment]
Should be (partially) fixed by #95.
There was still a chance of getting `ext_session_lock_surface_v1@xxx: error 2: committed surface dimensions do not match last acked configure`

**Comment by mochaaP** [comment]
the latter one is probably a gtk-session-lock issue (see `lock-surface.c:lock_surface_handle_configure`), cc'ing @Cu3PO42

**Comment by jovanlanik** [comment]
Should be fixed by #95 and https://github.com/jovanlanik/gtklock/commit/e0e7f6d5ae7667fcc3479b6732046c67275b2f2f.
