### ISSUE TITLE
Preview Style / No issue

### ISSUE THREAD

**Issue by Morriarthy** [jovanlanik/gtklock#75]
Is there a way/option to execute gtklock in a window (for example in hyprland) to preview the style changes I made?

**Comment by bhepple** [comment]
Try this:

```
$ gtklock -il
```

**Comment by Morriarthy** [comment]
Great, but it doesn't show the theme, fonts or wallpaper. 
Can I use it with a config/CSS-style-file like gtklock -il -c ~/.config/gtklock/style.css for example?
