### ISSUE TITLE
[Feature Request] Anti burn-in measures

### ISSUE THREAD

**Issue by jtfen86** [jovanlanik/gtklock#76]
Can you add an option to have the clock bounce around the screen instead of staying static? Also having the cursor hide itself after a set time would be nice. :)

**Comment by Jeidnx** [comment]
You can hide the cursor and the login form by setting `idle-hide=true` and `idle-timeout` to an amount of seconds after which they should hide

**Comment by jovanlanik** [comment]
Not planned.
