### ISSUE TITLE
[Hyprland]  ** (gtklock:7325): CRITICAL **: 13:15:53.447: Your compositor doesn't support wlr-input-inhibitor

### ISSUE THREAD

**Issue by nwg-piotr** [jovanlanik/gtklock#78]
Hi Jovan,

Since the last Hyprland update, gtklock refuses to work with the error message as above. Could anything be done about it?

**Comment by d3spairx** [comment]
Can confirm, `gtklock v2.1.0` and `Hyprland, built from branch  at commit e496b0f250139b572307d048f3189aa6dde72f18  ().`

**Comment by milesje** [comment]
same issue here...
using AUR version `aur/gtklock 2.1.0-2 (+6 0.67)`. I'm getting this output after upgrading to Kernel 6.6.4-arch1-1

**Comment by psoldunov** [comment]
Same here on Fedora 39
Kernel: `6.6.3-200.fc39.x86_64`
Hyprland:` 0.33.0-1`

**Comment by Lassebq** [comment]
Duplicate of #53 #77

**Comment by nwg-piotr** [comment]
> Duplicate of #53 #77

Closing, if so.
