### ISSUE TITLE
[Bug] Compositor does not support wlr-input-inhibitor 

### ISSUE THREAD

**Issue by utkarsh-singh1** [jovanlanik/gtklock#80]
Recently while using gtklock in hyprland -

```
** (gtklock:143920): CRITICAL **: 13:49:32.692: Your compositor doesn't support wlr-input-inhibitor
```

Also recently found this issue in hyprland - [#3932](https://github.com/hyprwm/Hyprland/issues/3932)

**Comment by RoccoRakete** [comment]
Same issue here! I hope this gets addressed.

**Comment by utkarsh-singh1** [comment]
/close

As a similar issue is already in work.
