### ISSUE TITLE
[Feature request] battery percentage module

### ISSUE THREAD

**Issue by werdahias** [jovanlanik/gtklock#85]
It would be great if there was a module to display battery percentage on the lockscreen

**Comment by jovanlanik** [comment]
Not planed at the moment but you can try using https://gitlab.com/wef/gtklock-runshell-module.
Maybe sometime in the future if I get to it.

**Comment by bhepple** [comment]
With runshell-module (I wrote it) I have battery and more on the lockscreen ...

![dump](https://github.com/jovanlanik/gtklock/assets/6417002/827c909a-d77a-47c5-bcde-73e94d91bf15)

**Comment by jovanlanik** [comment]
Not planned as a separate feature.
