### ISSUE TITLE
[session-lock] No keyboard input in hyprland

### ISSUE THREAD

**Issue by jovanlanik** [jovanlanik/gtklock#86]
> If anyone is interested in testing, I did a quick port in the [session-lock](/jovanlanik/gtklock/tree/session-lock) branch.

I gave the branch a quick try and managed to run it. On hyprland, I can confirm that it does indeed lock the screen, however it did not seem to capture any keyboard input, so it is impossible to enter a password. Mouse input works though.

_Originally posted by @haaase in https://github.com/jovanlanik/gtklock/issues/53#issuecomment-2042289402_

**Comment by jovanlanik** [comment]
@haaase can you try with the latest commit on the [session-lock](https://github.com/jovanlanik/gtklock/tree/session-lock) branch?

**Comment by SuchithSridhar** [comment]
I'm facing this problem with `hyprland` and `nixos` as well.

**Comment by jovanlanik** [comment]
@devraza This issue may only appear on multimonitor setups, are you using only one monitor?

**Comment by jovanlanik** [comment]
I think this and #89 are duplicate issues... I'm not sure so I'd keep both open for now.

**Comment by jovanlanik** [comment]
Thank you for the report.

**Comment by jovanlanik** [comment]
Can anyone test with the latest master?
