### ISSUE TITLE
Limited input in Hyprland with dual monitors

### ISSUE THREAD

**Issue by MonstrousOgre** [jovanlanik/gtklock#89]
Here is the exact behavior I'm experiencing.

- Using gtklock (without parameters) with both monitors connected, most input does not work.
  - Keyboard input doesn't work at all.
  - I can move the mouse but gtklock doesn't react to it. I can't focus the other monitor by moving the mouse there, and I can't focus the password box by clicking on it.
- I got it to work once on one monitor by specifying `--monitor-priority 1`. I could not reproduce this by calling the same command again though.
- Even the one time it worked with `--monitor-priority 1`, I could not focus the other monitor.
- Everything works fine when only one monitor is connected.

Hope this helps.

**Comment by jovanlanik** [comment]
Thanks for the detailed report.

The monitor priority option should be used with output names such as DP-1 or HDMI-A-2. Can you try that?

**Comment by jovanlanik** [comment]
Seems to be connected to this hyprwm/Hyprland/issues/5035

**Comment by MonstrousOgre** [comment]
> The monitor priority option should be used with output names such as DP-1 or HDMI-A-2. Can you try that?

Still doesn't seem to be working.

**Comment by tv42** [comment]
On https://github.com/YaLTeR/niri I usually end up with gtklock displaying clock + prompt on the laptop display and just the clock on the external monitor, with mouse pointer on the external monitor, and keyboard input ignored until I move the mouse to the laptop display.

Could gtklock take keyboard input also from the window (or whatever it is correctly called) that displays just the clock?

**Comment by MonstrousOgre** [comment]
Update: So the behavior is different as of Hyprland 0.41.1

- Keyboard and mouse input work on my primary monitor. I'm able to type and unlock the screen.
- When I move the mouse to my secondary monitor, the primary monitor gets unfocused but the secondary one does not get focused.
- I can focus my primary monitor again by moving my mouse back there.

**Comment by jovanlanik** [comment]
@MonstrousOgre Can you test the latest master? I added a `--folow-focus` option. Maybe some combination of that option and `--priority-monitor`...

**Comment by MonstrousOgre** [comment]
@jovanlanik I'm able to choose which monitor is focused using `--monitor-priority` but it can't focus another monitor once gtklock starts. Using `--follow-focus` makes no difference.

Regardless, it's usable now. I've made it my default screen locker.

**Comment by jovanlanik** [comment]
Thanks for testing. I'm glad it works for your use case.

I'd still like to have switching focus work because it seems it should be possible on hyprland...
Don't want to bother you with testing but could you try one more time with the latest?

**Comment by MonstrousOgre** [comment]
@jovanlanik it seems to be working with the latest master, and correctly switching focus. I don't even need to use `--follow-focus` or `--monitor-priority`.

Thanks a lot!
