### ISSUE TITLE
Cannot use GTK interactive debugger on gtklock

### ISSUE THREAD

**Issue by cry0x11** [jovanlanik/gtklock#91]
Is there a possible way to use `gtklock -li` as mentioned in the wiki?

Currently, `gtklock` doesn't recognize `-li` option

```Bash
** (gtklock:22403): CRITICAL **: 22:56:47.207: Option parsing failed: Unknown option -li
```

**Comment by jovanlanik** [comment]
Not supported in v3.0.0. An alternative way to debug may be included in a future version.

**Comment by cry0x11** [comment]
Alright, thank you for the reply. 

I figured out the values I should change from the wiki and other people's configurations.

And Thank you for putting in the effort to create this nice screenlocker :)
