### ISSUE TITLE
Crash and Red Screen at Unlock from Sleep

### ISSUE THREAD

**Issue by xi-pinmping** [jovanlanik/gtklock#92]
Not sure if anyone else is having this issue, but after my laptop locks and begins to go to sleep I am no longer able to unlock without a kernel segfault and the entire screen turning red. The end of my journal logs shows 

```

May 19 09:35:43 blabs gtklock[91036]: pam_winbind(gtklock:auth): getting password (0x00000000)
May 19 09:35:43 blabs gtklock[91036]: pam_winbind(gtklock:auth): request wbcLogonUser failed: WBC_ERR_WINBIND_NOT_AVAILABLE, PAM error: PAM_AUTHINFO_UNAVAIL (9)!
May 19 09:35:43 blabs gtklock[91036]: pam_winbind(gtklock:auth): internal module error (retval = PAM_AUTHINFO_UNAVAIL(9), user = 'user')
May 19 09:35:43 blabs unix_chkpwd[91097]: password check failed for user (user)
May 19 09:35:43 blabs gtklock[91036]: gkr-pam: the password for the login keyring was invalid.
May 19 09:35:44 blabs kernel: gtklock[91035]: segfault at ffffffffffffffff ip 000057ca9d647725 sp 00007068ffdffb70 error 7 in gtklock[57ca9d646000+4000] likely on CPU 15 (core 7, socket 0)
May 19 09:35:44 blabs kernel: Code: ef ff 15 26 67 00 00 48 89 da 8b 3d 55 6d 00 00 48 89 c6 48 89 05 5b 6d 00 00 48 89 e9 ff 15 a2 68 00 00 48 8b 15 4b 6d 00 00 <c6> 04 02 00 b8 03 00 00 00 48 8b 54 24 38 64 48 2b 14 25 28 00 00
lines 4873-4921/4921 (END)
```

Im not sure if maybe its a config im missing possibly but this only occurred in the last month with no notable config changes

```
sway --version 
sway version 1.9-8aa59c8 (Apr 10 2024, branch 'HEAD')

uname -a 
Linux blabs 6.9.1-2-cachyos #1 SMP PREEMPT_DYNAMIC Fri, 17 May 2024 14:24:05 +0000 x86_64 GNU/Linux

paru -Qi gtklock
Installed From  : None
Name            : gtklock
Version         : 3.0.0-1

```

**Comment by loganswartz** [comment]
I'm also getting this, it seems to happen for me only when the `userinfo-module` is enabled.

**Comment by xi-pinmping** [comment]
I just tried removing the userinfo-module but it still occurs even without the package installed and it disabled

**Comment by jovanlanik** [comment]
Do you have the same issue after d22127f?

**Comment by xi-pinmping** [comment]
> Do you have the same issue after [d22127f](https://github.com/jovanlanik/gtklock/commit/d22127f0fd61bbeba8c12378b3c5b46cc3064d63)?

I do still have the issue occurring. If I get to it soon enough (within minute or two) the issue does not appear but after going into deeper sleep the issue seems to reappear.

**Comment by xi-pinmping** [comment]
I just tried today and it finally didn't red screen but did just a day or two ago. Hopefully resolved but leaving open for a few more days incase its something else causing it

**Comment by LoneWolf4713** [comment]
hey umm, can anyone tell me how to fix this? I mean, this happened on gtklock (aur) 3.0.0-1 . I switched to gtklock-git (aur) to get the latest package, but now it's incompatible with all the modules (playerctl, powerbar and userinfo) they all support 3.0.0.-1, not the git version. so how can I fix this?

**Comment by xi-pinmping** [comment]
I believe it to be fixed now, my last few boots have seen extended sleep sessions without issue. Thanks a ton!
