### ISSUE TITLE
reft click on entry breaks everything

### ISSUE THREAD

**Issue by exoess** [jovanlanik/gtklock#93]
because of how gtk's entries work right clicking will pull up a popup menu that then gets put behind the lock screen, but the menu still pulls focus, meaning the lockscreen cannot be switched back to and the menu cannot be closed, there's a way to intercept the left click event to prevent this, but i don't remember how

**Comment by exoess** [comment]
something like this fixes it
```c
static gboolean entry_button_press(GtkWidget *widget, GdkEventButton *event,
                                   gpointer data) {
  if (event->button == 1) {
    return FALSE;
  }

  return TRUE;
}

struct Window *create_window(GdkMonitor *monitor) {
  ...
  
  w->input_field = GTK_WIDGET(gtk_builder_get_object(builder, "input-field"));

  g_signal_connect(GTK_ENTRY(w->input_field), "button-press-event",
                   G_CALLBACK(entry_button_press), NULL);
  
  ...
}
```

**Comment by jovanlanik** [comment]
Hi,

I would assume the context menu is opened on right click? Do you have any settings active to switch the mouse button actions? On my system left click selects the entry and right click opens the menu.

Also what kind of problem does the menu result in?

**Comment by exoess** [comment]
yea, right click, sorry, i'm dyslexic and mess up my right and left a lot

**Comment by exoess** [comment]
and for the issue, i described it
> the menu still pulls focus, meaning the lockscreen cannot be switched back to and the menu cannot be closed

**Comment by jovanlanik** [comment]
Which compositor are you using? On sway the focus stays on the lockscreen.

**Comment by exoess** [comment]
i had the issue on hyprland, it also just seems like a good idea to suppress this menu, it's ueeless in this case

**Comment by jovanlanik** [comment]
I agree

**Comment by jovanlanik** [comment]
Pushed the fix to master, thanks for the issue report and the fix code.

**Comment by exoess** [comment]
thanks :3
